export const HeaderTexts = {
  en: {
    'label.platform': 'Tycho Brahe Platform',
    'label.tool': 'Synviewer',
    'label.signout': 'sign out',
    'popover.option.add': 'Add',
    'popover.button.confirm': 'confirm',
    'popover.button.cancel': 'cancel',
    'popover.button.close': 'close',
    'label.corpora.available': 'Available Corpora',
    'label.my.settings': 'My Settings',
    'label.configurations': 'Configurations',
    'title.configurations': 'Breakpoints for parser',
    'pagination.label.showing': 'Showing',
    'pagination.label.results': 'results per page',
    'pagination.label.total': 'Total',
  },
  'pt-BR': {
    'label.platform': 'Plataforma Tycho Brahe',
    'label.tool': 'Synviewer',
    'label.signout': 'sair',
    'popover.option.add': 'Adicionar',
    'popover.button.confirm': 'confirmar',
    'popover.button.cancel': 'cancelar',
    'popover.button.close': 'fechar',
    'label.corpora.available': 'Corpora Disponíveis',
    'label.my.settings': 'Minhas Configurações',
    'label.configurations': 'Configurações',
    'title.configurations': 'Pontos de parada para o parser',
    'pagination.label.showing': 'Exibindo',
    'pagination.label.results': 'resultados por página',
    'pagination.label.total': 'Total',
  },
};
