export const HomeTexts = {
  en: {
    'err.invalid.id': 'ID inválido',
    'placeholder.parse.sentence': 'Insert sentence to parse',
    'placeholder.render.sentence': 'insert syntactic tree here',
    'placeholder.render.tycho': 'insert data here',
    'tab.label.parse': 'Parse Sentence',
    'tab.label.render': 'Render Syntactic Tree',
    'tab.label.tycho': 'Render Tycho Format',
    'tab.label.conllu': 'COnLL-U',
    'warning.parse.portuguese': 'Only available for Brazilian Portuguese',
    'button.label.parentheses': 'Convert to parentheses ( )',
    'button.label.brackets': 'Convert to brackets [ ]',
    'button.label.execute': 'Execute',
    'button.label.expand': 'Expand',
    'button.label.export': 'Export',
    'button.label.render': 'Render',
    'button.label.tycho': 'Tycho Parsers',
    'button.label.ud': 'Universal Dependencies',
    'placeholder.render.conllu':
      'Type or paste your CoNLL-U sentence to render',
    'ud.tree.title': 'Universal Dependencies Tree',
    'conllu.viewer.title': 'CoNLL-U Viewer',
  },
  'pt-BR': {
    'err.invalid.id': 'ID inválido',
    'placeholder.parse.sentence': 'Insira a sentença para realizar o parse',
    'placeholder.render.sentence': 'insira a árvore sintática aqui',
    'placeholder.render.tycho': 'insera os dados aqui',
    'tab.label.parse': 'Executar o Parser',
    'tab.label.render': 'Exibir Árvore Sintática',
    'tab.label.tycho': 'Exibir Formato Tycho',
    'warning.parse.portuguese': 'Disponível apenas para o Português Brasileiro',
    'button.label.parentheses': 'Converter para parênteses ( )',
    'button.label.brackets': 'Converter para colchetes [ ]',
    'button.label.execute': 'Executar',
    'button.label.expand': 'Expandir',
    'button.label.export': 'Exportar',
    'button.label.render': 'Exibir',
    'button.label.tycho': 'Parsers Tycho',
    'button.label.ud': 'Dependências Universais',
    'placeholder.render.conllu':
      'Digite ou cole sua sentença no formato CoNLL-U para exibir',
    'ud.tree.title': 'Árvores de Dependências Universais',
    'conllu.viewer.title': 'Visualizador CoNLL-U',
  },
};
