export const AppTexts = {
  en: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Graphical Editor',
    'tab.label.viewer': 'ConLL-U Viewer',
    'tab.label.tree': 'Tree',
    'button.label.export': 'Export',
    'button.label.render': 'Render',
    'button.label.ud': 'Universal Dependencies',
    'button.confirm': 'Confirm',
    'placeholder.render.conllu':
      'Type or paste your CoNLL-U sentence to render',
    'ud.tree.title': 'Universal Dependencies Tree',
    'conllu.viewer.title': 'CoNLL-U Viewer',
    'conllu.editor.title': 'CoNLL-U Editor',
    'conllu.graphical.title': 'Graphical Viewer',
    'tab.label.settings': 'Settings',
    'settings.title': 'Settings',
    'settings.placeholder': 'Settings content will be added here',
  },
  'pt-BR': {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Editor Gráfico',
    'tab.label.viewer': 'Visualizador CoNLL-U',
    'tab.label.tree': 'Árvore',
    'button.label.export': 'Exportar',
    'button.label.render': 'Exibir',
    'button.label.ud': 'Dependências Universais',
    'button.confirm': 'Confirmar',
    'placeholder.render.conllu':
      'Digite ou cole sua sentença no formato CoNLL-U para exibir',
    'ud.tree.title': 'Árvores de Dependências Universais',
    'conllu.viewer.title': 'Visualizador CoNLL-U',
    'conllu.editor.title': 'Editor CoNLL-U',
    'conllu.graphical.title': 'Visualizador Gráfico',
    'tab.label.settings': 'Configurações',
    'settings.title': 'Configurações',
    'settings.placeholder': 'O conteúdo das configurações será adicionado aqui',
  },
};
