export const AppTexts = {
  en: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Graphical Editor',
    'tab.label.viewer': 'ConLL-U Viewer',
    'tab.label.tree': 'Tree',
    'tab.label.settings': 'Settings',
    'label.empty': 'Empty',
    'button.label.export': 'Export',
    'button.label.render': 'Render',
    'button.label.ud': 'Universal Dependencies',
    'button.confirm': 'Confirm',
    'button.delete': 'Delete',
    'button.tooltip.recenter': 'Recenter',
    'button.tooltip.download': 'Download',
    'placeholder.render.conllu':
      'Type or paste your CoNLL-U sentence to render',
    'settings.title': 'Settings',
    'settings.language.label': 'Language',
    'settings.extendedUdTags.label': 'Extended UD Tags',
    'settings.extendedUdTags.placeholder': 'Enter tags separated by commas',
    'settings.extendedUdTags.helperText':
      'Add custom UD tags separated by commas (e.g., TAG1, TAG2, TAG3)',
    'token.details.title': 'Token Details',
    'token.details.tokenRange.label': 'TokenRange (in MISC)',
    'token.details.tokenRange.helperText':
      'Automatically calculated based on token form length',
    'token.details.misc.label': 'MISC (full)',
    'error.label.title': 'Ops, something went wrong',
    'error.label.redirect': 'Click here to go back to the home page',
    'error.label.details': 'Click here to see the error details',
  },
  'pt-BR': {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Editor Gráfico',
    'tab.label.viewer': 'Visualizador CoNLL-U',
    'tab.label.tree': 'Árvore',
    'tab.label.settings': 'Configurações',
    'label.empty': 'Vazio',
    'button.label.export': 'Exportar',
    'button.label.render': 'Exibir',
    'button.label.ud': 'Dependências Universais',
    'button.confirm': 'Confirmar',
    'button.delete': 'Excluir',
    'button.tooltip.recenter': 'Recentar',
    'button.tooltip.download': 'Download',
    'placeholder.render.conllu':
      'Digite ou cole sua sentença no formato CoNLL-U para exibir',
    'settings.title': 'Configurações',
    'settings.language.label': 'Idioma',
    'settings.extendedUdTags.label': 'Tags UD Estendidas',
    'settings.extendedUdTags.placeholder': 'Digite tags separadas por vírgulas',
    'settings.extendedUdTags.helperText':
      'Adicione tags UD personalizadas separadas por vírgulas (ex: TAG1, TAG2, TAG3)',
    'token.details.title': 'Detalhes do Token',
    'token.details.tokenRange.label': 'TokenRange (em MISC)',
    'token.details.tokenRange.helperText':
      'Calculado automaticamente com base no comprimento do token',
    'token.details.misc.label': 'MISC (completo)',
    'error.label.title': 'Ops, algo deu errado',
    'error.label.redirect': 'Ir para a home',
    'error.label.details': 'Clique aqui para ver os detalhes do erro',
  },
  it: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Editor Grafico',
    'tab.label.viewer': 'Visualizzatore CoNLL-U',
    'tab.label.tree': 'Albero',
    'tab.label.settings': 'Impostazioni',
    'label.empty': 'Vuoto',
    'button.label.export': 'Esporta',
    'button.label.render': 'Renderizza',
    'button.label.ud': 'Dipendenze Universali',
    'button.confirm': 'Conferma',
    'button.delete': 'Elimina',
    'button.tooltip.recenter': 'Ricentralizza',
    'button.tooltip.download': 'Scarica',
    'placeholder.render.conllu':
      'Digita o incolla la tua frase CoNLL-U per renderizzare',
    'settings.title': 'Impostazioni',
    'settings.language.label': 'Lingua',
    'settings.extendedUdTags.label': 'Tag UD Estesi',
    'settings.extendedUdTags.placeholder': 'Inserisci tag separati da virgole',
    'settings.extendedUdTags.helperText':
      'Aggiungi tag UD personalizzati separati da virgole (es: TAG1, TAG2, TAG3)',
    'token.details.title': 'Dettagli del Token',
    'token.details.tokenRange.label': 'TokenRange (in MISC)',
    'token.details.tokenRange.helperText':
      'Calcolato automaticamente in base alla lunghezza del token',
    'token.details.misc.label': 'MISC (completo)',
    'error.label.title': "Ops, quelque chose s'est mal passé",
    'error.label.redirect': 'Aller à la maison',
    'error.label.details': "Cliquez ici pour voir les détails de l'erreur",
  },
  fr: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Éditeur Graphique',
    'tab.label.viewer': 'Visualiseur CoNLL-U',
    'tab.label.tree': 'Arbre',
    'tab.label.settings': 'Paramètres',
    'label.empty': 'Vide',
    'button.label.export': 'Exporter',
    'button.label.render': 'Rendre',
    'button.label.ud': 'Dépendances Universelles',
    'button.confirm': 'Confirmer',
    'button.delete': 'Supprimer',
    'button.tooltip.recenter': 'Recentrer',
    'button.tooltip.download': 'Télécharger',
    'placeholder.render.conllu':
      'Tapez ou collez votre phrase CoNLL-U pour rendre',
    'settings.title': 'Paramètres',
    'settings.language.label': 'Langue',
    'settings.extendedUdTags.label': 'Tags UD Étendus',
    'settings.extendedUdTags.placeholder':
      'Entrez les tags séparés par des virgules',
    'settings.extendedUdTags.helperText':
      'Ajoutez des tags UD personnalisés séparés par des virgules (ex: TAG1, TAG2, TAG3)',
    'token.details.title': 'Détails du Token',
    'token.details.tokenRange.label': 'TokenRange (dans MISC)',
    'token.details.tokenRange.helperText':
      'Calculé automatiquement en fonction de la longueur du token',
    'token.details.misc.label': 'MISC (complet)',
    'error.label.title': "Ops, quelque chose s'est mal passé",
    'error.label.redirect': 'Aller à la maison',
    'error.label.details': "Cliquez ici pour voir les détails de l'erreur",
  },
  de: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Grafischer Editor',
    'tab.label.viewer': 'CoNLL-U Betrachter',
    'tab.label.tree': 'Baum',
    'tab.label.settings': 'Einstellungen',
    'label.empty': 'Leer',
    'button.label.export': 'Exportieren',
    'button.label.render': 'Rendern',
    'button.label.ud': 'Universelle Abhängigkeiten',
    'button.confirm': 'Bestätigen',
    'button.delete': 'Löschen',
    'button.tooltip.recenter': 'Zentrieren',
    'button.tooltip.download': 'Herunterladen',
    'placeholder.render.conllu':
      'Geben Sie Ihren CoNLL-U Satz ein oder fügen Sie ihn ein, um zu rendern',
    'settings.title': 'Einstellungen',
    'settings.language.label': 'Sprache',
    'settings.extendedUdTags.label': 'Erweiterte UD Tags',
    'settings.extendedUdTags.placeholder':
      'Tags durch Kommas getrennt eingeben',
    'settings.extendedUdTags.helperText':
      'Fügen Sie benutzerdefinierte UD Tags durch Kommas getrennt hinzu (z.B. TAG1, TAG2, TAG3)',
    'token.details.title': 'Token Details',
    'token.details.tokenRange.label': 'TokenRange (in MISC)',
    'token.details.tokenRange.helperText':
      'Automatisch basierend auf der Token-Länge berechnet',
    'token.details.misc.label': 'MISC (vollständig)',
    'error.label.title': 'Ops, etwas ist schief gelaufen',
    'error.label.redirect': 'Zurück zur Startseite',
    'error.label.details': 'Klicken Sie hier für Fehlerdetails',
  },
  es: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'Editor Gráfico',
    'tab.label.viewer': 'Visor CoNLL-U',
    'tab.label.tree': 'Árbol',
    'tab.label.settings': 'Configuración',
    'label.empty': 'Vacío',
    'button.label.export': 'Exportar',
    'button.label.render': 'Renderizar',
    'button.label.ud': 'Dependencias Universales',
    'button.confirm': 'Confirmar',
    'button.delete': 'Eliminar',
    'button.tooltip.recenter': 'Recentrar',
    'button.tooltip.download': 'Descargar',
    'placeholder.render.conllu':
      'Escribe o pega tu oración CoNLL-U para renderizar',
    'settings.title': 'Configuración',
    'settings.language.label': 'Idioma',
    'settings.extendedUdTags.label': 'Etiquetas UD Extendidas',
    'settings.extendedUdTags.placeholder':
      'Ingresa etiquetas separadas por comas',
    'settings.extendedUdTags.helperText':
      'Agrega etiquetas UD personalizadas separadas por comas (ej: TAG1, TAG2, TAG3)',
    'token.details.title': 'Detalles del Token',
    'token.details.tokenRange.label': 'TokenRange (en MISC)',
    'token.details.tokenRange.helperText':
      'Calculado automáticamente según la longitud del token',
    'token.details.misc.label': 'MISC (completo)',
    'error.label.title': 'Ops, algo salió mal',
    'error.label.redirect': 'Ir a la home',
    'error.label.details': 'Haga clic aquí para ver los detalles del error',
  },
  ar: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': 'المحرر الرسومي',
    'tab.label.viewer': 'عارض CoNLL-U',
    'tab.label.tree': 'شجرة',
    'tab.label.settings': 'الإعدادات',
    'label.empty': 'فارغ',
    'button.label.export': 'تصدير',
    'button.label.render': 'عرض',
    'button.label.ud': 'التبعيات العالمية',
    'button.confirm': 'تأكيد',
    'button.delete': 'حذف',
    'button.tooltip.recenter': 'إعادة التمركز',
    'button.tooltip.download': 'تحميل',
    'placeholder.render.conllu': 'اكتب أو الصق جملة CoNLL-U الخاصة بك للعرض',
    'settings.title': 'الإعدادات',
    'settings.language.label': 'اللغة',
    'settings.extendedUdTags.label': 'علامات UD الموسعة',
    'settings.extendedUdTags.placeholder': 'أدخل العلامات مفصولة بفواصل',
    'settings.extendedUdTags.helperText':
      'أضف علامات UD مخصصة مفصولة بفواصل (مثال: TAG1, TAG2, TAG3)',
    'token.details.title': 'تفاصيل الرمز المميز',
    'token.details.tokenRange.label': 'TokenRange (في MISC)',
    'token.details.tokenRange.helperText':
      'محسوب تلقائياً بناءً على طول الرمز المميز',
    'token.details.misc.label': 'MISC (كامل)',
    'error.label.title': 'Ops, حدث خطأ ما',
    'error.label.redirect': 'اضغط هنا للعودة إلى الرئيسية',
    'error.label.details': 'اضغط هنا لعرض تفاصيل الخطأ',
  },
  zh: {
    'tab.label.conllu': 'CoNLL-U',
    'tab.label.graphical': '图形编辑器',
    'tab.label.viewer': 'CoNLL-U 查看器',
    'tab.label.tree': '树',
    'tab.label.settings': '设置',
    'label.empty': '空',
    'button.label.export': '导出',
    'button.label.render': '渲染',
    'button.label.ud': '通用依存关系',
    'button.confirm': '确认',
    'button.delete': '删除',
    'button.tooltip.recenter': '重新居中',
    'button.tooltip.download': '下载',
    'placeholder.render.conllu': '输入或粘贴您的 CoNLL-U 句子以进行渲染',
    'settings.title': '设置',
    'settings.language.label': '语言',
    'settings.extendedUdTags.label': '扩展 UD 标签',
    'settings.extendedUdTags.placeholder': '输入用逗号分隔的标签',
    'settings.extendedUdTags.helperText':
      '添加用逗号分隔的自定义 UD 标签（例如：TAG1, TAG2, TAG3）',
    'token.details.title': '词元详情',
    'token.details.tokenRange.label': 'TokenRange（在 MISC 中）',
    'token.details.tokenRange.helperText': '根据词元长度自动计算',
    'token.details.misc.label': 'MISC（完整）',
    'error.label.title': 'Ops, 发生了错误',
    'error.label.redirect': '点击这里返回首页',
    'error.label.details': '点击这里以查看错误详情',
  },
};
